# These are supported funding model platforms

github: [danieldev23]

patreon:
open_collective:
ko_fi:
tidelift:
community_bridge:
liberapay:
issuehunt:
lfx_crowdfunding:
polar:
buy_me_a_coffee: huypc9294
thanks_dev:
custom:
